### ISSUE TITLE
Help with Setup

### ISSUE THREAD

**Issue by benwis** [rayliwell/tree-sitter-rstml#7]
Hi @rayliwell , I've been struggling a bit to setup this version of nvim-treesitter with either lunarvim or nvchad's neovim. If possible, I'd love to connect with you and discuss it. 

This is the error I'm getting:
```
Error detected while processing BufReadPost Autocommands for "*":                                                                                          
Installation not possible: ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:86: Parser not available for language "rstml"                       
See https://github.com/nvim-treesitter/nvim-treesitter/#adding-parsers on how to add a new parser!   
```

Thanks!
benwis

**Comment by rayliwell** [comment]
Hello @benwis, the main problem with neovim distros is that they hide the implementation details of the plugins they use.

Remove any config you've tried and all you should need to do is to go to the plugins folder (should be `~/.local/share/lunarvim/site/pack/lazy/opt` in lunarvim), then delete the `nvim-treesitter` folder, then `git clone https://github.com/rayliwell/nvim-treesitter`.

Then run `:TSInstall rstml`. This should work as long as you don't update your plugins (like with `:LvimUpdate`).

I will get to opening a pull request to nvim-treesitter soon so this isn't necessary anymore.

**Comment by rayliwell** [comment]
Also, sorry for just seeing that you wanted to get in contact.

DM me on discord at rayliwell if you need! 👍

**Comment by benwis** [comment]
Yeah, I'm trading some oddities for having almost everything set up already. Those instructions worked, I think
![2024-03-31-184140_1350x944_scrot](https://github.com/rayliwell/tree-sitter-rstml/assets/6953353/9de6c2b8-aed0-4317-9d03-a35ca645788b)

Ignore the weird boxes
